name: Translate CV

on:
  push:
    paths:
      - 'cv.json'
  workflow_dispatch:

jobs:
  translate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 9.15.4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm run translate-cv
        env:
          TRANSLATION_API_URL: ${{ secrets.TRANSLATION_API_URL }}
          TRANSLATION_API_KEY: ${{ secrets.TRANSLATION_API_KEY }}
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add cv.en.json
          if git diff --cached --quiet; then echo "No changes"; else git commit -m 'Update English CV translation'; git push; fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
